# Generated by Django 3.1.3 on 2023-06-16 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insectos', '0011_insecto_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='insecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Insectos', to='Insectos.insecto'),
        ),
    ]
